var _yt_www={};(function(g){var window=this;var baa,caa,ra,Ca,bb,kaa,cb,db,eb,fb,kb,laa,lb,maa,naa,sb,Db,Sb,qc,uaa,vaa,taa,Vc,Wc,bd,dd,yaa,id,md,gd,ed,Aaa,ld,jd,kd,od,zaa,td,Baa,Caa,Kd,Od,Qd,Rd,Sd,ee,se,Faa,Ce,Je,Ie,Haa,Iaa,Ke,Le,Ne,Kaa,Re,Xe,We,Se,af,Paa,ef,bf,cf,Oaa,hf,gf,kf,Ve,Pe,Oe,Qe,lf,Ze,jf,$e,nf,Raa,Naa,tf,uf,xf,Af,Cf,Qf,Rf,Sf,Vf,Xf,Yf,Zf,bg,ag,dg,$f,eg,Tf,Wf,aba,fg,gg,bba,cba,mg,og,qg,eba,xg,yg,Bg,zg,fba,Ig,Pg,Og,gba,Sg,mba,lba,kba,Yg,jba,hba,iba,nba,eh,oba,fh,hh,pba,qba,ih,jh,oh,sh,th,uh,xh,yh,zh,wba,xba,ph,rh,nh,vba,qh,Bba,Aba,Gh,
Hh,zba,Cba,Dba,Ih,Jh,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.da=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.n=function(a,b){for(var c=a.split("."),d=b||g.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.q=function(){throw Error("unimplemented abstract method");};
g.ga=function(a){a.getInstance=function(){return a.Ac?a.Ac:a.Ac=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ja=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ka=function(a){return"string"==typeof a};
g.la=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ha(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.r=function(a,b,c){g.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.r.apply(null,arguments)};
g.t=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.v=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.eW=function(a,c,h){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
ra=function(a){ra[" "](a);return a};
g.sa=function(a,b){try{return ra(a[b]),!0}catch(c){}return!1};
g.ta=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
g.ua=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ua);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.va=function(a,b){return 0==a.lastIndexOf(b,0)};
g.wa=function(a){return/^[\s\xa0]*$/.test(a)};
g.xa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.ya=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.za=function(a,b){return-1!=a.indexOf(b)};
g.Aa=function(a){return null==a?"":String(a)};
g.Da=function(a,b){for(var c=0,d=(0,g.Ba)(String(a)).split("."),e=(0,g.Ba)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var l=d[k]||"",p=e[k]||"";do{l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];if(0==l[0].length&&0==p[0].length)break;c=Ca(0==l[1].length?0:(0,window.parseInt)(l[1],10),0==p[1].length?0:(0,window.parseInt)(p[1],10))||Ca(0==l[2].length,0==p[2].length)||Ca(l[2],p[2]);l=l[3];p=p[3]}while(0==c)}return c};
Ca=function(a,b){return a<b?-1:a>b?1:0};
g.Ea=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Ha=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.ka(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ja=function(a,b){return 0<=(0,g.Ia)(a,b)};
g.La=function(a,b){var c=(0,g.Ia)(a,b),d;(d=0<=c)&&g.Ka(a,c);return d};
g.Ka=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Na=function(a){return function(){return a}};
g.Oa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Pa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ra=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Sa=function(a){for(var b in a)return!1;return!0};
g.Ta=function(a,b){b in a&&delete a[b]};
g.Ua=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Va=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Xa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Wa.length;h++)c=Wa[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Za=function(a){return g.za(g.Ya,a)};
g.$a=function(){return g.Za("Trident")||g.Za("MSIE")};
g.ab=function(){return(g.Za("Chrome")||g.Za("CriOS"))&&!g.Za("Edge")};
bb=function(a){g.ea.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Za("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.$a()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.da(c.next)){c=c.next;var a=c.cq;c.cq=null;a()}};
return function(a){d.next={cq:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.ea.setTimeout(a,0)}};
cb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
db=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
eb=function(){this.C=this.A=null};
fb=function(){this.next=this.scope=this.Cc=null};
kb=function(a,b){gb||laa();hb||(gb(),hb=!0);var c=ib,d=jb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.ea.Promise&&g.ea.Promise.resolve){var a=g.ea.Promise.resolve(void 0);gb=function(){a.then(lb)}}else gb=function(){var a=lb;
!g.na(g.ea.setImmediate)||g.ea.Window&&g.ea.Window.prototype&&!g.Za("Edge")&&g.ea.Window.prototype.setImmediate==g.ea.setImmediate?(mb||(mb=kaa()),mb(a)):g.ea.setImmediate(a)}};
lb=function(){for(var a;a=ib.remove();){try{a.Cc.call(a.scope)}catch(b){bb(b)}db(jb,a)}hb=!1};
g.nb=function(){this.Qd=this.Qd;this.Kb=this.Kb};
g.qb=function(a,b){g.ob(a,g.t(g.pb,b))};
g.ob=function(a,b){a.Qd?g.da(void 0)?b.call(void 0):b():(a.Kb||(a.Kb=[]),a.Kb.push(g.da(void 0)?(0,g.r)(b,void 0):b))};
g.pb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.rb=function(a){g.nb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.xd={};this.F=!!a};
maa=function(a,b,c){kb(function(){a.apply(b,c)})};
g.ub=function(a){sb(g.tb,arguments)};
g.x=function(a,b){return a in g.tb?g.tb[a]:b};
g.wb=function(a,b){g.na(a)&&(a=g.vb(a));return window.setTimeout(a,b)};
g.xb=function(a,b){g.na(a)&&(a=g.vb(a));return window.setInterval(a,b)};
g.yb=function(a){window.clearTimeout(a)};
g.zb=function(a){window.clearInterval(a)};
g.vb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Ab(b),b;}}:a};
g.Ab=function(a,b,c,d,e){var h=g.n("yt.logging.errors.log");h?h(a,b,c,d,e):(h=g.x("ERRORS",[]),h.push([a,b,c,d,e]),g.ub("ERRORS",h))};
naa=function(a,b,c,d,e){var h=!1;if(g.tb.sp&&g.tb.sp.log_window_onerror_fraction&&Math.random()<g.tb.sp.log_window_onerror_fraction)h=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,p=k.length;l<p;l++)if(0<k[l].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Ab(e))};
g.Cb=function(a){return a in g.Bb};
sb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.y=function(a,b,c){var d=Db();if(d){var e=d.subscribe(a,function(){if(!Eb||Eb!=e){var d=arguments,k;k=function(){Fb[e]&&b.apply(c||window,d)};
try{Gb[a]?k():g.wb(k,0)}catch(l){g.Ab(l)}}},c);
Fb[e]=!0;Hb[a]||(Hb[a]=[]);Hb[a].push(e);return e}return 0};
g.Ib=function(a){var b=Db();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.z)(a,function(a){b.unsubscribeByKey(a);delete Fb[a]}))};
g.A=function(a,b){var c=Db();return c?c.publish.apply(c,arguments):!1};
g.Jb=function(a,b){Gb[a]=!0;var c=Db(),c=c?c.publish.apply(c,arguments):!1;Gb[a]=!1;return c};
Db=function(){return g.n("yt.pubsub.instance_")};
g.Kb=function(){return!!g.n("yt.scheduler.instance")};
g.Lb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.n("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.wb(a,b||0)};
g.Mb=function(a,b){return g.Lb(a,b)};
g.Nb=function(a){if(!(0,window.isNaN)(a)){var b=g.n("yt.scheduler.instance.cancelJob");b?b(a):g.yb(a)}};
g.Ob=function(a){for(var b=0,c=a.length;b<c;b++)g.Nb(a[b])};
g.Pb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.vb(d):null;this.F=e?g.vb(e):null;this.D=[];this.A=this.C=0};
g.Qb=function(a){g.Nb(a.C);a.C=g.Mb((0,g.r)(a.init,a))};
g.Tb=function(a){a.name in Rb&&Sb(a.name);Rb[a.name]={reqs:[],disable:(0,g.r)(a.disable,a)};(0,g.z)(a.deps,function(b){if(!(b in Rb))throw Error("Module "+b+" required by "+a.name);Rb[b].reqs.push(a.name)});
a.enable()};
Sb=function(a){if(a in Rb){var b=Rb[a];(0,g.z)(b.reqs,function(a){Sb(a)});
try{b.disable()}catch(c){}delete Rb[a]}};
g.Wb=function(){this.A="";this.C=g.Vb};
g.Xb=function(a){var b=new g.Wb;b.A=a;return b};
g.Zb=function(){this.A="";this.C=Yb};
g.$b=function(a){if(a instanceof g.Zb&&a.constructor===g.Zb&&a.C===Yb)return a.A;g.ha(a);return"type_error:SafeUrl"};
g.bc=function(a){if(a instanceof g.Zb)return a;a=a.Yf?a.Ue():String(a);oaa.test(a)||(a="about:invalid#zClosurez");return g.ac(a)};
g.ac=function(a){var b=new g.Zb;b.A=a;return b};
g.ec=function(){this.A="";this.B=g.cc;this.C=null};
g.fc=function(a,b){var c=new g.ec;c.A=a;c.C=b;return c};
g.hc=function(a,b){g.gc(a);var c;c=b instanceof g.Zb?b:g.bc(b);a.href=g.$b(c)};
g.gc=function(a){g.oa(a)&&(a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a))};
g.B=function(a,b){return a?a.dataset?a.dataset[g.ic(b)]:a.getAttribute("data-"+b):null};
g.ic=function(a){return jc[a]||(jc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.lc=function(a,b){var c=g.kc(a);window.spf.script.load(a,c,b)};
g.kc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(paa,""),b=b.replace(qaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.mc=function(a){if(a.classList)return a.classList;a=a.className;return g.ka(a)&&a.match(/\S+/g)||[]};
g.C=function(a,b){return a.classList?a.classList.contains(b):g.Ja(g.mc(a),b)};
g.nc=function(a,b){this.x=g.da(a)?a:0;this.y=g.da(b)?b:0};
g.oc=function(a,b){this.width=a;this.height=b};
g.pc=function(){return g.Za("iPhone")&&!g.Za("iPod")&&!g.Za("iPad")};
qc=function(){var a=g.ea.document;return a?a.documentMode:void 0};
g.sc=function(a){return g.ta(raa,a,function(){return 0<=g.Da(g.rc,a)})};
g.uc=function(a){return Number(g.tc)>=a};
g.D=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.vc=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.xc=function(a,b){g.Oa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:wc.hasOwnProperty(d)?a.setAttribute(wc[d],b):g.va(d,"aria-")||g.va(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.zc=function(a){return g.yc(a||window)};
g.yc=function(a){a=a.document;a=g.Ac(a)?a.documentElement:a.body;return new g.oc(a.clientWidth,a.clientHeight)};
g.Cc=function(a){var b=g.Bc(a);a=a.parentWindow||a.defaultView;return g.E&&g.sc("10")&&a.pageYOffset!=b.scrollTop?new g.nc(b.scrollLeft,b.scrollTop):new g.nc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Bc=function(a){return a.scrollingElement?a.scrollingElement:!g.Dc&&g.Ac(a)?a.documentElement:a.body||a.documentElement};
g.Fc=function(a,b,c){return g.Ec(window.document,arguments)};
g.Ec=function(a,b){var c=String(b[0]),d=b[1];if(!saa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.ya(d.name),'"');if(d.type){c.push(' type="',g.ya(d.type),'"');var e={};g.Xa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ka(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.xc(c,d));2<b.length&&g.Gc(a,c,b,2);return c};
g.Gc=function(a,b,c,d){function e(c){c&&b.appendChild(g.ka(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ja(h)||g.oa(h)&&0<h.nodeType?e(h):(0,g.z)(taa(h)?g.Ma(h):h,e)}};
g.Ac=function(a){return"CSS1Compat"==a.compatMode};
g.Hc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Ic=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Jc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
uaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
vaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Kc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
taa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.Lc=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Nc=function(a){var b=a.__yt_uid_key;b||(b=Mc(),a.__yt_uid_key=b);return b};
g.Oc=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.z)(a.childNodes,function(a){b.appendChild(g.Oc(a))}):b.innerHTML=a.innerHTML;
return b};
g.Pc=function(){var a=window.document;if("visibilityState"in a)return a.visibilityState;var b=waa+"VisibilityState";if(b in a)return a[b]};
g.Qc=function(a){return g.x("EXPERIMENT_FLAGS",{})[a]};
g.Rc=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};
g.Sc=function(a){a=String(a);if(g.Rc(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};
g.Uc=function(a,b){return(new g.Tc(b)).Ob(a)};
g.Tc=function(a){this.A=a};
Vc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(g.ia(b)){var d=b;b=d.length;c.push("[");for(var e="",h=0;h<b;h++)c.push(e),e=d[h],Vc(a,a.A?a.A.call(d,String(h),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");h="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(h),Wc(d,c),c.push(":"),Vc(a,a.A?a.A.call(b,d,e):e,c),h=","));c.push("}");return}}switch(typeof b){case "string":Wc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};
Wc=function(a,b){b.push('"',a.replace(xaa,function(a){var b=Xc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Xc[a]=b);return b}),'"')};
g.Yc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.Zc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.ad=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.H=!1;if(a!=g.fa)try{var c=this;a.call(b,function(a){g.$c(c,2,a)},function(a){g.$c(c,3,a)})}catch(d){g.$c(this,3,d)}};
bd=function(){this.next=this.context=this.C=this.B=this.A=null;this.D=!1};
dd=function(a,b,c){var d=cd.get();d.B=a;d.C=b;d.context=c;return d};
yaa=function(a,b,c){ed(a,b,c,null)||kb(g.t(b,a))};
g.fd=function(a){return new g.ad(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,p;l<a.length;l++)p=a[l],yaa(p,g.t(h,l),k);
else b(e)})};
g.hd=function(a,b){gd(a,null,b,void 0)};
id=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,h=null,k=c.C;k&&(k.D||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(h=k);e&&(0==c.A&&1==d?id(c,b):(h?(d=h,d.next==c.D&&(c.D=d),d.next=d.next.next):jd(c),kd(c,e,3,b)))}a.B=null}else g.$c(a,3,b)};
md=function(a,b){a.C||2!=a.A&&3!=a.A||ld(a);a.D?a.D.next=b:a.C=b;a.D=b};
gd=function(a,b,c,d){var e=dd(null,null,null);e.A=new g.ad(function(a,k){e.B=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.da(e)&&b instanceof g.nd?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;md(a,e);return e.A};
g.$c=function(a,b,c){0==a.A&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,ed(c,a.R,a.Y,a)||(a.K=c,a.A=b,a.B=null,ld(a),3!=b||c instanceof g.nd||zaa(a,c)))};
ed=function(a,b,c,d){if(a instanceof g.ad)return md(a,dd(b||g.fa,c||null,d)),!0;if(g.Zc(a))return a.then(b,c,d),!0;if(g.oa(a))try{var e=a.then;if(g.na(e))return Aaa(a,e,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1};
Aaa=function(a,b,c,d,e){function h(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,h)}catch(p){h(p)}};
ld=function(a){a.H||(a.H=!0,kb(a.G,a))};
jd=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
kd=function(a,b,c,d){if(3==c&&b.C&&!b.D)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,od(b,c,d);else try{b.D?b.B.call(b.context):od(b,c,d)}catch(e){pd.call(null,e)}db(cd,b)};
od=function(a,b,c){2==b?a.B.call(a.context,c):a.C&&a.C.call(a.context,c)};
zaa=function(a,b){a.F=!0;kb(function(){a.F&&pd.call(null,b)})};
g.nd=function(a){g.ua.call(this,a)};
g.qd=function(){return{apiaryHost:g.x("APIARY_HOST",void 0),Op:g.x("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.x("GAPI_HINT_OVERRIDE"),gapiHintParams:g.x("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.x("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.x("INNERTUBE_API_VERSION",void 0),NE:g.x("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.x("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),PE:g.x("INNERTUBE_CONTEXT_HL",void 0),OE:g.x("INNERTUBE_CONTEXT_GL",void 0),dQ:g.x("XHR_APIARY_HOST",
void 0)}};
g.rd=function(a){a={client:{hl:a.PE,gl:a.OE,clientName:a.NE,clientVersion:a.innertubeContextClientVersion}};g.x("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.x("DELEGATED_SESSION_ID")});return a};
td=function(){this.A=g.qd();sd||(sd=Baa(this.A))};
Baa=function(a){return(new g.ad(function(b){g.lc(g.x("GAPI_LOADER_URL",void 0),function(){try{g.n("yt.gapi.load")("client",{gapiHintOverride:a.gapiHintOverride,_c:{jsl:{h:a.gapiHintParams}},callback:b})}catch(c){g.Ab(c)}})})).then(function(){})};
Caa=function(a,b,c,d){var e={path:"/youtubei/"+a.A.innertubeApiVersion+"/"+b,headers:{"X-Goog-Visitor-Id":g.x("VISITOR_DATA")},method:"POST",body:g.Uc(c)},h=(0,g.r)(a.D,a);sd.then(function(){h();g.n("gapi.client.request")(e).execute(d||g.fa)})};
g.ud=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.vd=function(a){var b={};void 0!==a.A?b.trackingParams=a.A:(b.veType=a.B,null!=a.C&&(b.veCounter=a.C));return b};
g.Ad=function(a,b){g.wd[a.endpoint]=g.wd[a.endpoint]||[];var c=g.wd[a.endpoint];c.push(a.Bb);xd[a.endpoint]=b;20<=c.length?g.yd():g.zd()};
g.yd=function(){g.yb(g.Bd);if(!g.Sa(g.wd)){for(var a in g.wd){var b=g.Cd[a];if(!b){b=xd[a];if(!b)continue;b=new b;g.Cd[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.Dd)());c[Daa[a]]=g.wd[a];b.B(a,c,{});delete g.wd[a]}g.Sa(g.wd)||g.zd()}};
g.zd=function(){g.yb(g.Bd);g.Bd=g.wb(g.yd,g.x("LOGGING_BATCH_TIMEOUT",1E4))};
g.Ed=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.Dd)());e[a]=b;g.Ad({endpoint:"log_event",Bb:e},c)};
g.Fd=function(){};
g.Hd=function(a){if(a instanceof g.Fd)return a;if("function"==typeof a.Xb)return a.Xb(!1);if(g.ja(a)){var b=0,c=new g.Fd;c.next=function(){for(;;){if(b>=a.length)throw g.Gd;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");};
g.Id=function(a,b,c){if(g.ja(a))try{(0,g.z)(a,b,c)}catch(d){if(d!==g.Gd)throw d;}else{a=g.Hd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Gd)throw d;}}};
g.Jd=function(a){if(g.ja(a))return g.Ma(a);a=g.Hd(a);var b=[];g.Id(a,function(a){b.push(a)});
return b};
Kd=function(){};
g.Ld=function(){};
g.Md=function(a){this.A=a};
g.Nd=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.A=a};
Od=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.A=a};
g.Pd=function(a){this.A=a};
Qd=function(a){this.A=a};
Rd=function(a){this.data=a};
Sd=function(a){return!g.da(a)||a instanceof Rd?a:new Rd(a)};
g.Td=function(a){this.A=a};
g.Ud=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,g.F)()||!!b&&b>(0,g.F)()};
g.Vd=function(a){this.A=a};
g.Yd=function(a){if(!g.Wd&&!g.Xd||!window.JSON)return null;var b;try{b=g.Wd.get(a)}catch(c){}if(!g.ka(b))try{b=g.Xd.get(a)}catch(c){}if(!g.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(c){}return b};
g.Zd=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Eaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.In=a.pageX;this.Jn=a.pageY}};
g.ae=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ra(g.$d,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.G=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.ae(a,b,c,d);if(e)return e;var e=++be.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.Zd(d);if(!g.Lc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Zd(b);
b.currentTarget=a;return c.call(a,b)};
k=g.vb(k);a.addEventListener?("mouseenter"==b&&h?b="mouseover":"mouseleave"==b&&h?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.$d[e]=[a,b,c,k,d];return e};
g.ce=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.z)(a,function(a){if(a in g.$d){var c=g.$d[a],d=c[0],e=c[1],h=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,h,c):d.detachEvent&&d.detachEvent("on"+e,h);delete g.$d[a]}}))};
g.de=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.fe=function(){if(null==g.n("_lact",window)){var a=(0,window.parseInt)(g.x("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&ee();g.G(window.document,"keydown",ee);g.G(window.document,"keyup",ee);g.G(window.document,"mousedown",ee);g.G(window.document,"mouseup",ee);g.y("page-mouse",ee);g.y("page-scroll",ee);g.y("page-resize",ee)}};
ee=function(){null==g.n("_lact",window)&&(g.fe(),g.n("_lact",window));var a=(0,g.F)();g.m("_lact",a,window);g.A("USER_ACTIVE")};
g.ge=function(){var a=g.n("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
g.he=function(){return g.Yd("yt-interaction-logging-parent")};
g.ie=function(){var a=g.x("client-screen-nonce",void 0);a||(a=g.x("EVENT_ID",void 0));return a};
g.je=function(a,b,c,d,e,h,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);h&&(l+="?"+h);k&&(l+="#"+k);return l};
g.ke=function(a){return a?(0,window.decodeURI)(a):a};
g.me=function(a,b){return b.match(g.le)[a]||null};
g.ne=function(a){return g.ke(g.me(3,a))};
g.oe=function(a){a=a.match(g.le);return g.je(null,null,null,null,a[5],a[6],a[7])};
g.pe=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.qe=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.re=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.re(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.xa(b))};
se=function(a,b){for(var c in b)g.re(c,b[c],a);return a};
g.te=function(a){a=se([],a);a[0]="";return a.join("")};
g.ue=function(a,b){return g.qe(se([a],b))};
g.ve=function(a,b,c){a&&(c&&(c=g.Ya,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Fc("IFRAME",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Kc(a).body.appendChild(a)):Faa(a,b))};
g.we=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.ve(a,void 0)}catch(b){g.ve(a,void 0)}};
Faa=function(a,b){var c=new window.Image,d=""+Gaa++;xe[d]=c;c.onload=c.onerror=function(){b&&xe[d]&&b();delete xe[d]};
c.src=a};
g.ye=function(a,b){this.version=a;this.args=b};
g.ze=function(a,b){this.topic=a;this.zf=b};
g.Be=function(a,b){var c=g.Ae();return c?c.publish.call(c,a.toString(),a,b):!1};
g.Ae=function(){return g.n("yt.pubsub2.instance_")};
Ce=function(a){g.ye.call(this,1,arguments)};
g.De=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Ee=function(a,b){return a&&b?b instanceof g.De?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Fe=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.Ge=function(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top),h=Math.min(a.top+a.height,b.top+b.height);if(e<=h)return a.left=c,a.top=e,a.width=d-c,a.height=h-e,!0}return!1};
g.He=function(a){return new g.oc(a.width,a.height)};
Je=function(a){this.A=a||window;this.R=this.B=0;if(this.A.performance&&this.A.performance.timing&&this.A.performance.getEntriesByType){a=g.zc(this.A);this.G=new g.Fe(0,0,a.width,a.height);a=[];for(var b=this.A.document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++){var e=b[c];if("IMG"==e.tagName||"IFRAME"==e.tagName){var h=Ie(this,e,e.src);if(h){if("IFRAME"==e.tagName){var k;try{k=(new Je(e.contentWindow)).B}catch(l){k=0}0<k&&(h.timing=k)}a.push(h)}}(h=this.A.getComputedStyle(e)["background-image"])&&
(h=Je.A.exec(h))&&1<h.length&&(h=Ie(this,e,h[1]))&&a.push(h)}this.C=a;this.F=this.A.performance.getEntriesByType("resource");this.K=this.A.performance.getEntriesByType("mark");k={};a=0;for(b=this.F.length;a<b;a++)c=this.F[a],k[c.name]=c.responseEnd;a=0;for(b=this.K.length;a<b;a++)c=this.K[a],"mark_iframe_loaded: "==c.name.slice(0,20)&&(k[c.name.slice(20)]=c.startTime);a=0;for(b=this.C.length;a<b;a++)c=this.C[a],c.timing||(c.timing=k[c.url]||0);this.H=Haa(this);this.D=Iaa(this);e=k=0;if(this.D.length)for(b=
a=0,c=this.D.length;b<c;b++)d=this.D[b],e=d.timing-e,0<e&&1>a&&(k+=(1-a)*e),e=d.timing,a=d.progress;this.B=Math.round(k||this.H);this.R=e}};
Ie=function(a,b,c){return c&&b.getBoundingClientRect&&(b=b.getBoundingClientRect(),b=new g.Fe(b.left,b.top,b.width,b.height),g.Ge(b,a.G))?new Ke(b,c):null};
Haa=function(a){var b,c=a.A,d=c.performance.timing.navigationStart;if("msFirstPaint"in c.performance.timing)b=c.performance.timing.A-d;else if("chrome"in c&&"loadTimes"in c.chrome){var e=c.chrome.loadTimes(),h=e.firstPaintTime;if(0<h){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);h>=k&&(b=1E3*(h-k))}}if(void 0===b||0>b||12E4<b){b=c.performance.timing.responseStart-d;for(var l={},c=c.document.getElementsByTagName("head")[0].children,d=0,e=c.length;d<e;d++)h=c[d],"SCRIPT"==h.tagName&&h.src&&
!h.async?l[h.src]=!0:"LINK"==h.tagName&&"stylesheet"==h.rel&&h.href&&(l[h.href]=!0);a.F.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===b||a>b)b=a})}return Math.max(b,0)||0};
Iaa=function(a){for(var b={0:0},c=0,d=a.H,e=0,h=a.C.length;e<h;e++){var k=a.C[e],l=d;k.timing>d&&(l=k.timing);b[l]||(b[l]=0);k=g.He(k.region).yg();b[l]+=k;c+=k}e=g.He(a.G).yg();0<e&&(e=.1*Math.max(e-c,0),d in b||(b[d]=0),b[d]+=e,c+=e);d=[];if(c){for(var p in b)a=new Le((0,window.parseFloat)(p),b[p]),d.push(a);d.sort(function(a,b){return a.timing-b.timing});
e=b=0;for(h=d.length;e<h;e++)a=d[e],b+=a.yg,a.progress=b/c}return d};
Ke=function(a,b){this.region=a;this.url=b};
Le=function(a,b){this.yg=b;this.timing=a};
Ne=function(a){Me.mark&&(Jaa.test(a)||(a="mark_"+a),Me.mark(a))};
Kaa=function(){if("cold"==Oe().yt_lt){var a=Pe(),b=Qe(),c;for(c in a)g.va(c,"_")||"tick_"+c in b||Re(c,a[c]);a=Oe();for(c in a)"info_"+c in b||Se(c,a[c])}};
g.Ue=function(a,b,c){b||"_"==a[0]||Ne(a);var d=Pe(c),e=b||(0,g.Dd)();d[a]&&(d["_"+a]=d["_"+a]||[d[a]],d["_"+a].push(e));d[a]=e;Re(a,b,c)||g.Te(!1,c);return d[a]};
Re=function(a,b,c){Qe(c)["tick_"+a]=b;return g.Qc("csi_on_gel")?(c=Ve(c),"_start"==a?g.Ed("latencyActionBaselined",{clientActionNonce:c},td,b):g.Ed("latencyActionTicked",{tickName:a,clientActionNonce:c},td,b),!0):!1};
Xe=function(a,b){We("yt_sts",a,void 0);g.Ue("_start",b,void 0)};
We=function(a,b,c){Oe(c)[a]=b;Se(a,b,c)};
Se=function(a,b,c){Qe(c)["info_"+a]=b;if(g.Qc("csi_on_gel"))if(a in Ye){var d={};a=Ye[a];g.Ja(Laa,a)&&(b=!!b);d[a]=b;b=Ve(c);d.clientActionNonce=b;g.Ed("latencyActionInfo",d,td)}else g.Ab(Error("Unknown label "+a+" logged with GEL CSI."))};
af=function(a){Ze(a);Maa();$e(!1,a)};
Paa=function(){var a=g.x("TIMING_INFO",{}),b;for(b in a)We(b,a[b]);(a=g.ie())&&We("csn",a);(a=g.x("PREVIOUS_ACTION",void 0))&&We("pa",a);a=Oe();a.p=g.x("CLIENT_PROTOCOL")||"unknown";a.t=g.x("CLIENT_TRANSPORT")||"unknown";Me.now&&Me.timing?(a=Me.timing.navigationStart+Me.now(),a=Math.round((0,g.F)()-a)):a=null;null!=a&&We("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&We("ba",1);We("yt_vis",Naa());if("cold"==Oe().yt_lt){a=Me.timing||{};g.Qc("cold_load_nav_start_web")&&a.navigationStart&&
(Xe("n",a.navigationStart),g.Ue("srt",a.responseStart));a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=b.loadTimes,g.na(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.Ue("fpt",b);bf(a);Me.getEntriesByType&&Oaa();a=g.x("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.x("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.Dd)(),
b=new Je,c=(0,g.Dd)(),0<b.B&&(We("si",b.B),g.Ue("vsc",cf(b.R)),g.Ue("sics",a),g.Ue("sice",c)));a=[];if(window.document.querySelector&&Me&&Me.getEntriesByName)for(var d in df)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=Me.getEntriesByName(c))&&b[0]&&a.push(df[d]+"."+Math.round(b[0].duration))}a.length&&We("rs",a.join(","))}};
ef=function(a){var b=Pe(a);if(b.aft)return b.aft;a=g.x((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
bf=function(a){g.Ue("nreqs",a.requestStart,void 0);g.Ue("nress",a.responseStart,void 0);g.Ue("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.Ue("nrs",a.redirectStart,void 0),g.Ue("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.Ue("ndnss",a.domainLookupStart,void 0),g.Ue("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.Ue("ntcps",a.connectStart,void 0),g.Ue("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.Ue("nstcps",a.secureConnectionStart,void 0),g.Ue("ntcpe",a.connectEnd,void 0))};
cf=function(a){return Math.round(Me.timing.navigationStart+a)};
Oaa=function(){var a=window.location.protocol,b=Me.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.Ue("wfcs",cf(c.startTime)),g.Ue("wfce",cf(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.Ue("wffs",cf(b.startTime)),g.Ue("wffe",cf(b.responseEnd)))};
hf=function(a){var b=Pe(a),c=Oe(a),d=b._start,e;for(e in b)if(g.va(e,"_")&&g.ia(b[e])){var h=e.slice(1);if(h in Qaa){var k=(0,g.ff)(b[e],function(a){return Math.round(a-d)});
c["all_"+h]=k.join()}delete b[e]}h=!!c.ap;if(k=g.n("yt.timing.reportbuilder_")){if(k=k(b,c,a))gf(k,h),af(a)}else{var l=g.x("CSI_SERVICE_NAME","youtube"),k={v:2,s:l,action:g.x((a||"")+"TIMING_ACTION",void 0)},p=c.srt;delete c.srt;void 0===b.srt&&(p||0===p||(p=Me.timing||{},p=Math.max(0,p.responseStart-p.navigationStart),(0,window.isNaN)(p)&&c.pt&&(p=c.pt)),p||0===p)&&(c.srt=Math.round(p));if(c.h5jse){var u=window.location.protocol+g.n("ytplayer.config.assets.js");(u=Me.getEntriesByName?Me.getEntriesByName(u)[0]:
null)?c.h5jse=Math.round(c.h5jse-u.responseEnd):delete c.h5jse}b.aft=ef(a);Raa(a)&&"youtube"==l&&(We("yt_lt","hot_bg",a),l=b.vc,u=b.pbs,delete b.aft,c.aft=Math.round(u-l));for(var w in c)"_"!=w.charAt(0)&&(k[w]=c[w]);b.ps=(0,g.Dd)();c={};w=[];for(e in b)"_"!=e.charAt(0)&&(l=Math.round(b[e]-d),c[e]=l,w.push(e+"."+l));k.rt=w.join(",");(b=g.n("ytdebug.logTiming"))&&b(k,c);g.Qc("navigation_only_csi_reset")||af(a);gf(k,h,a);g.Be(Saa,new Ce(c.aft+(p||0)))}};
g.Te=function(a,b){if(!jf(b)||!g.Qc("navigation_only_csi_reset")&&!b){var c=g.x((b||"")+"TIMING_ACTION",void 0),d=Pe(b);if(g.n("yt.timing."+(b||"")+"ready_")&&c&&d._start&&ef(b))if(a||b)hf(b);else{var c=!0,e=g.x("TIMING_WAIT",[]);if(e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}c&&hf(b)}}};
gf=function(a,b,c){if(g.Qc("debug_csi_data")){var d=g.n("yt.timing.csiData");d||(d=[],g.m("yt.timing.csiData",d,void 0));d.push({page:window.location.href,time:new Date,args:a})}var d="",e;for(e in a)d+="&"+e+"="+a[e];a="/csi_204?"+d.substring(1);window.navigator&&window.navigator.sendBeacon&&b?g.we(a):g.ve(a);$e(!0,c)};
kf=function(a){g.m("yt.timing.ready_",a,void 0)};
Ve=function(a){var b=lf(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(h){}c=Array(16);for(d=0;16>d;d++){e=(0,g.F)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(mf)for(d=1,e=0;e<mf.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^mf.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");lf(a).nonce=b}return b};
Pe=function(a){return lf(a).tick};
Oe=function(a){return lf(a).info};
Qe=function(a){a=lf(a);"gel"in a||(a.gel={});return a.gel};
lf=function(a){return g.n("ytcsi."+(a||"")+"data_")||Ze(a)};
Ze=function(a){var b={tick:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
jf=function(a){return!!g.n("yt.timing."+(a||"")+"pingSent_")};
$e=function(a,b){g.m("yt.timing."+(b||"")+"pingSent_",a,void 0)};
nf=function(a){if(!jf(void 0)){if(!g.Qc("send_empty_timing")){var b=g.x("CSI_SERVICE_NAME","youtube");if(!g.x("TIMING_ACTION",void 0)||!b)return}g.Ue("aa",void 0,void 0);We("ap",1,void 0);We("yt_fss",a,void 0);hf(void 0)}};
Raa=function(a){var b=Pe(a),c=b.pbr,d=b.vc,b=b.pbs;return c&&d&&b&&c<d&&d<b&&1==Oe(a).yt_pvis};
Naa=function(){switch(g.Pc()){case "hidden":return 0;case "visible":return 1;case "prerender":return 2;case "unloaded":return 3}return-1};
g.of=function(a){this.A=a||{cookie:""}};
g.qf=function(a){a=(a.A.cookie||"").split(g.pf);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.sf=function(a,b,c,d){g.rf.set(""+a,b,c,"/",d||"youtube.com")};
g.vf=function(a,b,c){var d=g.x("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.ne(window.location.href);e&&d.push(e);e=g.ne(a);if(g.Ja(d,e)||!e&&g.va(a,"/"))if(a=g.oe(a),a=g.pe(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(tf(a,b,c),uf(b))):(tf(a,b),uf(b))};
tf=function(a,b,c){a="ST-"+g.Ea(a).toString(36);c=c||5;b=b?g.te(b):"";g.sf(a,b,c)};
uf=function(a){if(a){a=a.itct||a.ved;var b=g.n("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.ud(a))}};
g.wf=function(a,b){g.ve("/gen_204?"+a,b)};
xf=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Va(Taa);this.assets=a.assets||{};this.attrs=a.attrs||g.Va(Uaa);this.params=a.params||g.Va(Vaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.yf=function(a){a instanceof xf||(a=new xf(a));return a};
Af=function(){return null!=g.zf};
g.Bf=function(){return g.zf?g.zf.invoke():null};
Cf=function(){return(0,window.parseInt)(g.x("DCLKSTAT",0),10)};
g.Df=function(a,b,c){c=c||"";g.hc(window.location,g.ue(a,b||{})+c)};
g.Ef=function(a,b){b&&g.vf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.Df(a)};
g.Ff=function(a,b,c){var d=g.x("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.vf(a,b);if(c)return!1;g.Ef(a);return!0};
g.Gf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Hf=function(a,b){a.style.height=g.Gf(b,!0)};
g.If=function(a,b){a.style.width=g.Gf(b,!0)};
g.Kf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.n("window.navigator.plugins"),b=g.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,p,u;if(g.Jf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else p=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=p.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}p&&u&&p.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
g.Lf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
g.Mf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
g.Nf=function(a){return-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!g.Lf(a,9,1,58)?!1:!0};
g.Of=function(a,b,c){if(b){a=g.ka(a)?g.vc(a):a;var d=g.Va(c.attrs);d.tabindex=0;var e=g.Va(c.params);e.flashvars=g.te(c.args);if(g.Jf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Pf=function(a,b){var c=a.match(Waa);window.spf.style.load(a,c?c[1]:"",b)};
Qf=function(a){g.nb.call(this);this.A=[];this.C=a||this};
Rf=function(a,b,c,d){d=g.vb((0,g.r)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Lb:d})};
Sf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Lb)}};
Vf=function(a,b){g.nb.call(this);this.K=this.D=a;this.ia=b;this.H=!1;this.api={};this.la=this.T=null;this.X=new g.rb;g.qb(this,this.X);this.B={};this.G=this.Ra=this.C=this.jb=this.A=null;this.aa=!1;this.R=this.F=this.M=this.P=null;this.Wa={};this.Ib=["onReady"];this.ea=new Qf(this);g.qb(this,this.ea);this.mb=null;this.xb=window.NaN;this.ga={};Tf(this);this.le("onDetailedError",(0,g.r)(this.SJ,this));this.le("onTabOrderChange",(0,g.r)(this.ez,this));this.le("onTabAnnounce",(0,g.r)(this.Hp,this));this.le("WATCH_LATER_VIDEO_ADDED",
(0,g.r)(this.VJ,this));this.le("WATCH_LATER_VIDEO_REMOVED",(0,g.r)(this.WJ,this));g.Uf||(this.le("onMouseWheelCapture",(0,g.r)(this.AJ,this)),this.le("onMouseWheelRelease",(0,g.r)(this.BJ,this)));this.le("onAdAnnounce",(0,g.r)(this.Hp,this));this.Y=new Qf(this);g.qb(this,this.Y);this.bb=!1;this.ab=null};
Xf=function(a,b){a.jb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ia,a.A.attrs.id=a.ia);a.K.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ia;a.Ra||(a.Ra=Wf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.If(a.K,Number(c)||c);(c=a.A.attrs.height)&&g.Hf(a.K,Number(c)||c)};
Yf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
Zf=function(a){if(!g.da(a.A.disable.flash)){var b=a.A.disable,c;c=g.Lf(g.Kf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
bg=function(a,b){if((!b||(5!=(Xaa[b.errorCode]||5)?0:-1!=Yaa.indexOf(b.errorCode)))&&Zf(a)){var c=$f(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.yf(c));d.args.autoplay=1;d.args.html5_unavailable="1";Xf(a,d);ag(a,"flash")}};
ag=function(a,b){if(!a.gb()){if(!b){var c;if(!(c=!a.A.html5&&Zf(a))){if(!g.da(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==cg)d=!0;else{a:{var e=c;c=g.n("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?Zaa:$aa,h=0;h<e.length;h++)if(c.canPlayType(e[h])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&(d=dg(a)||
a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?Zf(a)?"flash":"unsupported":"html5"}("flash"==b?a.bQ:a.cQ).call(a)}};
dg=function(a){var b=!0,c=$f(a);c&&a.A&&(a=a.A,b=g.B(c,"version")==a.assets.js);return b&&!!g.n("yt.player.Application.create")};
$f=function(a){var b=g.D(a.C);!b&&a.K&&a.K.querySelector&&(b=a.K.querySelector("#"+a.C));return b};
eg=function(a,b,c){var d=b[c];return function(){try{return a.mb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.mb=e,g.Ab(e,"WARNING"))}}};
Tf=function(a){a.H=!1;if(a.la)for(var b in a.B)a.la(b,a.B[b]);for(var c in a.ga)g.yb((0,window.parseInt)(c,10));a.ga={};a.T=null;a.la=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.r)(a.le,a);a.api.removeEventListener=(0,g.r)(a.iO,a);a.api.destroy=(0,g.r)(a.dispose,a);a.api.getLastError=(0,g.r)(a.FA,a);a.api.getPlayerType=(0,g.r)(a.VA,a);a.api.getCurrentVideoConfig=(0,g.r)(a.cA,a);a.api.loadNewVideoConfig=(0,g.r)(a.Xo,a);a.api.isReady=(0,g.r)(a.qQ,a)};
Wf=function(a,b){var c=b;if("string"==typeof b){if(a.Wa[b])return a.Wa[b];c=function(){var a=g.n(b);a&&a.apply(g.ea,arguments)};
a.Wa[b]=c}return c?c:null};
aba=function(a,b){var c="ytPlayer"+b+a.ia;a.B[b]=c;g.ea[c]=function(c){var e=g.wb(function(){a.gb()||(a.X.Ea(b,c),g.Ta(a.ga,String(e)))},0);
g.Ua(a.ga,String(e),!0)};
return c};
fg=function(a){return(a=$f(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
gg=function(a){g.Ue("dcp");a.cancel();Tf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=$f(a);"html5"==fg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Hc(a.D);Sf(a.ea);a.F=null;a.R=null};
g.jg=function(a,b){a=g.ka(a)?g.vc(a):a;b=g.yf(b);var c=g.hg+"_"+g.qa(a),d=g.ig[c];if(d)return d.Xo(b),d.api;d=new Vf(a,c);g.ig[c]=d;g.A("player-added",d.api);g.ob(d,g.t(bba,d));g.wb(function(){d.Xo(b)},0);
return d.api};
bba=function(a){g.ig[a.getId()]=null};
g.kg=function(a){a=g.D(a);if(!a)return null;var b=g.hg+"_"+g.qa(a),c=g.ig[b];c||(c=new Vf(a,b),g.ig[b]=c);return c.api};
g.lg=function(){return g.C(g.D("page-container"),"remote-connected")};
cba=function(){g.m("yt.abuse.botguardInitialized",Af,void 0);g.m("yt.abuse.invokeBotguard",g.Bf,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",Cf,void 0);g.m("yt.player.exports.navigate",g.Ff,void 0);g.m("yt.player.embed",g.jg,void 0);g.m("yt.player.getPlayerByElement",g.kg,void 0);g.m("yt.util.activity.init",g.fe,void 0);g.m("yt.util.activity.getTimeSinceActive",g.ge,void 0);g.m("yt.util.activity.setTimestamp",ee,void 0);var a=g.n("ytplayer.config");mg(a);g.n("ytspf.enabled")&&(ng=g.xb(og,5E3),
(a=g.pg())?(a.addEventListener("onReady",og),a.addEventListener("onStateChange",og)):qg("unable to init PP monitor"))};
mg=function(a){for(var b in g.ig){var c=g.ig[b];c&&c.cancel()}if(a=a||null){b=g.pg();var d=!0,c=g.rg;g.rg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(sg="",g.jg("player-api",a)):b.playVideo();a=g.yf(a);a.loaded=!0}og();g.m("ytplayer.config",a,void 0)};
g.pg=function(){var a=g.n("yt.player.getPlayerByElement");return a?a("player-api"):null};
og=function(){var a=g.pg();if(a){var b;b=g.D("player");b=!b||g.C(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.x("PAGE_NAME"),e=g.lg();!c||d||e||(qg("PP playing off watch (paused)"),a.pauseVideo());b&&d?qg("PP off-screen on watch"):b||d||qg("PP !off-screen off watch")}};
qg=function(a){var b=g.x("PAGE_NAME");b&&(b=[b,sg,g.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Ab(Error(a),"WARNING"))};
g.tg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.hg=!1;this.Zv=!0};
g.ug=function(a,b){g.tg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.Mn=!1;this.ub=null;a&&this.init(a,b)};
g.wg=function(a){return!(!a||!a[vg])};
eba=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.Ch=!!d;this.td=e;this.key=++dba;this.Yg=this.Zi=!1};
xg=function(a){a.Yg=!0;a.listener=null;a.A=null;a.src=null;a.td=null};
yg=function(a){this.src=a;this.A={};this.C=0};
g.Ag=function(a,b,c,d,e,h){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.C++);var l=zg(b,c,e,h);-1<l?(a=b[l],d||(a.Zi=!1)):(a=new eba(c,a.src,k,!!e,h),a.Zi=d,b.push(a));return a};
Bg=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.La(a.A[c],b);d&&(xg(b),0==a.A[c].length&&(delete a.A[c],a.C--));return d};
g.Cg=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=zg(a,c,d,e));return-1<b?a[b]:null};
zg=function(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.Yg&&h.listener==b&&h.Ch==!!c&&h.td==d)return e}return-1};
g.Dg=function(a,b,c,d,e){if(g.ia(b)){for(var h=0;h<b.length;h++)g.Dg(a,b[h],c,d,e);return null}c=g.Eg(c);return g.wg(a)?a.O(b,c,d,e):g.Fg(a,b,c,!1,d,e)};
g.Fg=function(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var k=!!e,l=g.Gg(a);l||(a[Hg]=l=new yg(a));c=g.Ag(l,b,c,d,e,h);if(c.A)return c;d=fba();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Ig(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Jg++;return c};
fba=function(){var a=gba,b=Kg?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.Lg=function(a,b,c,d,e){if(g.ia(b))for(var h=0;h<b.length;h++)g.Lg(a,b[h],c,d,e);else c=g.Eg(c),g.wg(a)?a.Va(b,c,d,e):a&&(a=g.Gg(a))&&(b=g.Cg(a,b,c,!!d,e))&&g.Mg(b)};
g.Mg=function(a){if(g.la(a)||!a||a.Yg)return!1;var b=a.src;if(g.wg(b))return Bg(b.Y,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.Ch):b.detachEvent&&b.detachEvent(Ig(c),d);Jg--;(c=g.Gg(b))?(Bg(c,a),0==c.C&&(c.src=null,b[Hg]=null)):xg(a);return!0};
Ig=function(a){return a in Ng?Ng[a]:Ng[a]="on"+a};
Pg=function(a,b,c,d){var e=!0;if(a=g.Gg(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.Ch==c&&!h.Yg&&(h=Og(h,d),e=e&&!1!==h)}return e};
Og=function(a,b){var c=a.listener,d=a.td||a.src;a.Zi&&g.Mg(a);return c.call(d,b)};
gba=function(a,b){if(a.Yg)return!0;if(!Kg){var c=b||g.n("window.event"),d=new g.ug(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var h=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){h=!0}if(h||void 0==c.returnValue)c.returnValue=!0}c=[];for(h=d.currentTarget;h;h=h.parentNode)c.push(h);for(var h=a.type,k=c.length-1;!d.hg&&0<=k;k--){d.currentTarget=c[k];var l=Pg(c[k],h,!0,d),e=e&&l}for(k=0;!d.hg&&k<c.length;k++)d.currentTarget=c[k],l=Pg(c[k],h,!1,d),e=e&&l}return e}return Og(a,new g.ug(b,
this))};
g.Gg=function(a){a=a[Hg];return a instanceof yg?a:null};
g.Eg=function(a){if(g.na(a))return a;a[Qg]||(a[Qg]=function(b){return a.handleEvent(b)});
return a[Qg]};
g.Rg=function(){g.nb.call(this);this.Y=new yg(this);this.jy=this;this.Po=null};
Sg=function(a,b,c,d){b=a.Y.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var k=b[h];if(k&&!k.Yg&&k.Ch==c){var l=k.listener,p=k.td||k.src;k.Zi&&Bg(a.Y,k);e=!1!==l.call(p,d)&&e}}return e&&0!=d.Zv};
g.Tg=function(a,b,c){if(g.na(a))c&&(a=(0,g.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,g.r)(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:g.ea.setTimeout(a,b||0)};
g.Ug=function(a){g.ea.clearTimeout(a)};
g.Vg=function(a,b,c){g.nb.call(this);this.A=a;this.B=b||0;this.C=c;this.Lc=(0,g.r)(this.cm,this)};
mba=function(){Wg++;var a=g.zc(),b=new g.Fe(0,0,a.width,a.height);We("vps",a.width+"."+a.height);g.Ue("vpc");var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0;Xg.start();for(var h=0;h<c;h++){var k=a[h];if(Yg(k,b)){var l=hba(k);l.then(iba);d.push(l);Zg.push(l);k.loadTime||(e=!1)}}e&&We("yt_eil",1);We("vpni",d.length);g.Ue("vpcc");b=g.fd(d).then(jba);g.hd(b,kba);b.then(lba);Zg.push(b);return b};
lba=function(){Xg.stop()};
kba=function(){g.Ue("vpr")};
Yg=function(a,b){for(var c=a,d=window.document.body;c!=d;){var e=g.Nc(c);if(e in $g)break;var h=window.getComputedStyle(c);if("none"==h.display||"hidden"==h.visibility)return!1;h=c.getBoundingClientRect();if(!(b.left<=h.left+h.width&&h.left<=b.left+b.width&&b.top<=h.top+h.height&&h.top<=b.top+b.height))return!1;$g[e]=!0;c=c.parentElement}return!0};
jba=function(a){for(var b=g.zc(),b=new g.Fe(0,0,b.width,b.height),c=0,d=0,e=a.length;d<e;d++){var h=a[d].time;Yg(a[d].C,b)&&c<h&&(c=h)}return c};
hba=function(a){var b=Wg;return new g.ad(function(c,d){var e={C:a,time:0};if(a.loadTime)e.time=(0,window.parseInt)(a.loadTime,10),c(e);else{var h=g.G(a,"load",function(){Wg!=b&&(g.ce(h),d());if(a.loadTime){var k=(0,window.parseInt)(a.loadTime,10);g.ce(h);e.time=k;c(e)}});
ah.push(h)}})};
iba=function(a){Xg.start();We("vpil",++bh);a=a.time;ch<a&&(ch=a,g.Ue("lim",a))};
nba=function(){g.Ue("vptl",ch);g.Ue("vpl",ch)};
eh=function(){g.Ue("ol");window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Ue("cpt")},0)}):window.document.hidden?g.Ue("cpt"):(0,window.setTimeout)(function(){g.Ue("cpt")},0);
oba();g.x("CSI_VIEWPORT")&&(dh=mba(),dh.then(function(a){g.Ue("vpl",a);dh=null},function(){}))};
oba=function(){fh("init");var a=g.x("PAGE_NAME",void 0);a&&fh("init-"+a)};
fh=function(a){g.Kb()?gh.push(g.Lb(g.t(g.Jb,a),0)):g.A(a)};
hh=function(){g.Ob(gh);gh.length=0;for(var a=Zg.length,b=0;b<a;b++)Zg[b].cancel();ch=bh=Zg.length=0;$g={};g.ce(ah);ah.length=0;dh&&(dh.cancel(),dh=null);(a=g.x("PAGE_NAME",void 0))&&g.Jb("dispose-"+a);g.Jb("dispose")};
pba=function(){eh()};
qba=function(){g.x("TIMING_REPORT_ON_UNLOAD")&&g.Te(!0);nf("u");hh();g.Jb("pageunload")};
ih=function(){ee()};
jh=function(a){a=a.detail.url;window.yt_spf_loaded_history=!0;ee();var b=g.he();if(b&&a){var c=g.vd(b.visualElement),b={csn:b.clientScreenNonce};"trackingParams"in c?b.itct=c.trackingParams:(b.veType=c.veType,b.veCounter=c.veCounter);g.vf(a,b)}};
oh=function(){kh=1;lh=mh=0;g.x("TIMING_REPORT_ON_UNLOAD")&&g.Te(!0);nf("n");af();Xe("n");Ne("nr");nh(rba);g.Jb("navigate")};
sh=function(a){a=a.detail.part||a.detail.partial;g.Ue("nc"+mh);++mh;if(a.data&&a.data.deferDispose)"watch"==a.name&&g.Ue("bc");else{var b=1==kh;kh=2;b?(nh(sba),ph()):nh(tba);if(b=a.data&&a.data.swfcfg)qh(a.timing,b.args),rh(b)}};
th=function(){g.Ue("np"+lh);++lh};
uh=function(a){a=a.detail.response;var b=1==kh;kh=3;b&&(nh(uba),ph());if(b=a.data&&a.data.swfcfg)qh(a.timing,b.args),rh(b)};
xh=function(a){g.Ue("nd");a=a.detail.response;g.vh=a.cacheKey;a=a.timing;var b=window._spf_state;We("yt_nav",b&&b["nav-counter"]||0);Xe("ne",a.responseStart);We("srt",Math.max(0,a.responseStart-a.navigationStart));We("yt_lt",a.spfCached?"hot":"warm");We("yt_pft",+!!a.spfPrefetched);g.Ue("pfs",a.fetchStart);g.Ue("pfrs",a.responseStart);"redirectStart"in a&&bf(a);nh(wh);window.document.getElementById("content").style.height="";eh();kh=0};
yh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Ab(a)};
zh=function(a){g.wf(g.te({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
wba=function(){vba();g.ub("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
xba=function(){};
ph=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");hh();var a=g.x("TIMING_ACTION"),b;for(b in g.tb)delete g.tb[b];g.ub("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.pg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())sg=b,(b=g.D("movie_player"))&&b.stopVideo?(b.stopVideo(),sg="recovered"):sg="missing2"}else sg="missing";og()};
rh=function(a){"cfg"in Pe(void 0)||g.Ue("cfg");mg(a)};
nh=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Nb(Ah);Ah=g.Mb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.yb(Bh);Bh=g.wb(function(){b.className=e},c)},0)};
vba=function(){var a=wh[0]+50;g.yb(Bh);Bh=g.wb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
qh=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.z)(yba,function(a){a in b&&(delete b[a],e.push(a))});
g.x("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.wf(g.te(c)))};
Bba=function(a){g.Ch&&!g.Dh&&!g.Eh&&!g.Fh&&a.pushManager&&("default"!=window.Notification.permission?Gh(a).then(zba):g.x("SERVICE_WORKER_PROMPT_NOTIFICATIONS",void 0)&&Aba(a))};
Aba=function(a){a&&g.x("LOGGED_IN",void 0)&&window.Notification.requestPermission().then(function(b){"granted"==b?Gh(a).then(Hh):"denied"==b&&Hh()})};
Gh=function(a){return a.pushManager.getSubscription().then(function(b){return b?window.Promise.resolve():a.pushManager.subscribe({userVisibleOnly:!0}).then(function(){return window.Promise.resolve()})})};
Hh=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_register",data:g.x("ID_TOKEN")})};
zba=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_check_registration",data:g.x("ID_TOKEN")})};
Cba=function(){var a="/sw.js",b=g.x("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"});g.Qc("service_worker_push_enabled")&&window.navigator.serviceWorker.ready.then(Bba)};
Dba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"})};
Ih=function(){g.Pb.call(this,"www/base");this.B=0};
Jh=function(a){(a=a.detail.name)&&Sb(a)};
g.aa=[];g.Kh=g.Kh||{};g.ea=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};ra[" "]=g.fa;g.v(g.ua,Error);g.ua.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Ba=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.Lh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.Eba=2147483648*Math.random()|0;g.Ia=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ka(a))return g.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Fba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ka(a))return g.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.z=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.Mh=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.ka(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var p=k[l];
b.call(c,p,l,a)&&(e[h++]=p)}return e};
g.ff=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.ka(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.Nh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.r)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.z)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.Oh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.Ph=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.Qh=g.Na(!1);g.Rh=g.Na(!0);g.Sh=g.Na(null);var Wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Th=g.ea.navigator;if(Th){var Uh=Th.userAgent;if(Uh){g.Ya=Uh;break a}}g.Ya=""};var mb;cb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var jb=new cb(function(){return new fb},function(a){a.reset()},100);
eb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
fb.prototype.set=function(a,b){this.Cc=a;this.scope=b;this.next=null};
fb.prototype.reset=function(){this.next=this.scope=this.Cc=null};var gb,hb=!1,ib=new eb;g.nb.prototype.Qd=!1;g.nb.prototype.gb=function(){return this.Qd};
g.nb.prototype.dispose=function(){this.Qd||(this.Qd=!0,this.U())};
g.nb.prototype.U=function(){if(this.Kb)for(;this.Kb.length;)this.Kb.shift()()};g.v(g.rb,g.nb);g.f=g.rb.prototype;g.f.subscribe=function(a,b,c){var d=this.xd[a];d||(d=this.xd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.xd[a]){var d=this.A;if(a=g.Ha(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.yd(a)}return!1};
g.f.yd=function(a){var b=this.A[a];if(b){var c=this.xd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.fa):(c&&g.La(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.Ea=function(a,b){var c=this.xd[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.yd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.xd[a];b&&((0,g.z)(b,this.yd,this),delete this.xd[a])}else this.A.length=0,this.xd={}};
g.f.ob=g.ba(3);g.f.U=function(){g.rb.L.U.call(this);this.clear();this.C.length=0};g.tb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.tb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Bb=window.yt&&window.yt.msgs_||g.n("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Bb,void 0);g.Dd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Jf="Microsoft Internet Explorer"==window.navigator.appName;var Gba=g.n("yt.pubsub.instance_")||new g.rb;g.rb.prototype.subscribe=g.rb.prototype.subscribe;g.rb.prototype.unsubscribeByKey=g.rb.prototype.yd;g.rb.prototype.publish=g.rb.prototype.Ea;g.rb.prototype.clear=g.rb.prototype.clear;g.m("yt.pubsub.instance_",Gba,void 0);var Fb=g.n("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Fb,void 0);var Hb=g.n("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Hb,void 0);var Gb=g.n("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Gb,void 0);var Eb=g.n("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Eb,void 0);g.f=g.Pb.prototype;g.f.wO=function(){this.Xj()||this.init()};
g.f.enable=function(){this.A=1;(0,g.z)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.wO,this),this.subscribe("dispose-"+a,this.dispose,this),g.x("PAGE_NAME")==a&&g.Qb(this))},this)};
g.f.init=function(){g.Nb(this.C);this.A=2;this.H&&this.H()};
g.f.Xj=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Nb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Ab(a)}};
g.f.subscribe=function(a,b,c){a=g.y(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Ib(this.D);this.D=[]};var Rb=g.n("yt.modules.registry_")||{};g.m("yt.modules.registry_",Rb,void 0);g.Hba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Iba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Vh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Wb.prototype.Yf=!0;g.Vb={};g.Wb.prototype.Ue=function(){return this.A};
g.Jba=g.Xb("");g.Zb.prototype.Yf=!0;g.Zb.prototype.Ue=function(){return this.A};
g.Zb.prototype.Om=!0;g.Zb.prototype.Te=g.ba(5);var oaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Yb={};g.ac("about:blank");g.ec.prototype.Om=!0;g.ec.prototype.Te=g.ba(4);g.ec.prototype.Yf=!0;g.ec.prototype.Ue=function(){return this.A};
g.cc={};g.Kba=g.fc("<!DOCTYPE html>",0);g.Wh=g.fc("",0);g.Xh=g.fc("<br>",0);var jc={};var paa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,qaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Lba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.nc.prototype;g.f.clone=function(){return new g.nc(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.la(b)?b:a;this.x*=a;this.y*=c;return this};g.f=g.oc.prototype;g.f.clone=function(){return new g.oc(this.width,this.height)};
g.f.yg=function(){return this.width*this.height};
g.f.aspectRatio=function(){return this.width/this.height};
g.f.isEmpty=function(){return!this.yg()};
g.f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.la(b)?b:a;this.width*=a;this.height*=c;return this};var di,ei,raa,ii;g.Yh=g.Za("Opera");g.E=g.$a();g.Zh=g.Za("Edge");g.$h=g.Zh||g.E;g.ai=g.Za("Gecko")&&!(g.za(g.Ya.toLowerCase(),"webkit")&&!g.Za("Edge"))&&!(g.Za("Trident")||g.Za("MSIE"))&&!g.Za("Edge");g.Dc=g.za(g.Ya.toLowerCase(),"webkit")&&!g.Za("Edge");g.Dc&&g.Za("Mobile");g.bi=g.Za("Macintosh");g.ci=g.Za("Windows");g.Mba=g.Za("Linux")||g.Za("CrOS");di=g.ea.navigator||null;di&&g.za(di.appVersion||"","X11");g.Nba=g.Za("Android");g.Eh=g.pc();g.Fh=g.Za("iPad");g.Oba=g.Za("iPod");
a:{var fi="",gi=function(){var a=g.Ya;if(g.ai)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Zh)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Dc)return/WebKit\/(\S+)/.exec(a);if(g.Yh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
gi&&(fi=gi?gi[1]:"");if(g.E){var hi=qc();if(null!=hi&&hi>(0,window.parseFloat)(fi)){ei=String(hi);break a}}ei=fi}g.rc=ei;raa={};ii=g.ea.document;g.tc=ii&&g.E?qc()||("CSS1Compat"==ii.compatMode?(0,window.parseInt)(g.rc,10):5):void 0;var saa;saa=!g.E||g.uc(9);g.Pba=!g.ai&&!g.E||g.E&&g.uc(9)||g.ai&&g.sc("1.9.1");g.ji=g.E&&!g.sc("9");g.Qba=g.E||g.Yh||g.Dc;g.Rba=g.E&&!g.uc(9);var wc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};var waa=g.Dc?"webkit":g.ai?"moz":g.E?"ms":g.Yh?"o":"",Mc=g.n("yt.dom.getNextId_");if(!Mc){Mc=function(){return++Sba};
g.m("yt.dom.getNextId_",Mc,void 0);var Sba=0};g.Tc.prototype.Ob=function(a){var b=[];Vc(this,a,b);return b.join("")};
var Xc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;bd.prototype.reset=function(){this.context=this.C=this.B=this.A=null;this.D=!1};
var cd=new cb(function(){return new bd},function(a){a.reset()},100);
g.ad.prototype.then=function(a,b,c){return gd(this,g.na(a)?a:null,g.na(b)?b:null,c)};
g.Yc(g.ad);g.ad.prototype.cancel=function(a){0==this.A&&kb(function(){var b=new g.nd(a);id(this,b)},this)};
g.ad.prototype.R=function(a){this.A=0;g.$c(this,2,a)};
g.ad.prototype.Y=function(a){this.A=0;g.$c(this,3,a)};
g.ad.prototype.G=function(){for(var a;a=jd(this);)kd(this,a,this.A,this.K);this.H=!1};
var pd=bb;g.v(g.nd,g.ua);g.nd.prototype.name="cancel";var sd=null;td.prototype.D=function(){var a=g.n("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);var b=this.A.apiaryHost;g.wa(g.Aa(b))||a("googleapis.config/root",(-1==b.indexOf("://")?"//":"")+b);b=this.A.Op;g.wa(g.Aa(b))||a("googleapis.config/root-1p",(-1==b.indexOf("://")?"//":"")+b);a("googleapis.config/sessionIndex",g.x("SESSION_INDEX"));g.n("gapi.client.setApiKey")(this.A.innertubeApiKey)};
td.prototype.C=function(){return{context:g.rd(this.A)}};
td.prototype.B=function(a,b,c){var d,e=!1;0<c.timeout&&(d=g.wb(function(){e||(e=!0,c.sc&&c.sc())},c.timeout));
Caa(this,a,b,function(a){if(!e)if(e=!0,d&&g.yb(d),a)c.W&&c.W(a);else if(c.onError)c.onError()})};var Daa,xd;Daa={log_event:"events",log_interaction:"interactions"};g.Cd={};xd={};g.Bd=0;g.wd=g.n("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.wd,void 0);g.Gd="StopIteration"in g.ea?g.ea.StopIteration:{message:"StopIteration",stack:""};g.Fd.prototype.next=function(){throw g.Gd;};
g.Fd.prototype.Xb=function(){return this};Kd.prototype.set=g.q;Kd.prototype.get=g.q;Kd.prototype.remove=g.q;g.v(g.Ld,Kd);g.Ld.prototype.ob=g.ba(2);g.Ld.prototype.Xb=g.q;g.Ld.prototype.clear=function(){var a=g.Jd(this.Xb(!0)),b=this;(0,g.z)(a,function(a){b.remove(a)})};g.v(g.Md,g.Ld);g.f=g.Md.prototype;g.f.isAvailable=function(){if(!this.A)return!1;try{return this.A.setItem("__sak","1"),this.A.removeItem("__sak"),!0}catch(a){return!1}};
g.f.set=function(a,b){try{this.A.setItem(a,b)}catch(c){if(0==this.A.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};
g.f.get=function(a){a=this.A.getItem(a);if(!g.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
g.f.remove=function(a){this.A.removeItem(a)};
g.f.ob=g.ba(1);g.f.Xb=function(a){var b=0,c=this.A,d=new g.Fd;d.next=function(){if(b>=c.length)throw g.Gd;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!g.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};
return d};
g.f.clear=function(){this.A.clear()};
g.f.key=function(a){return this.A.key(a)};g.v(g.Nd,g.Md);g.v(Od,g.Md);g.Pd.prototype.set=function(a,b){g.da(b)?this.A.set(a,g.Uc(b)):this.A.remove(a)};
g.Pd.prototype.get=function(a){var b;try{b=this.A.get(a)}catch(c){return}if(null!==b)try{return g.Sc(b)}catch(c){throw"Storage: Invalid value was encountered";}};
g.Pd.prototype.remove=function(a){this.A.remove(a)};g.v(Qd,g.Pd);Qd.prototype.set=function(a,b){Qd.L.set.call(this,a,Sd(b))};
Qd.prototype.C=function(a){a=Qd.L.get.call(this,a);if(!g.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};
Qd.prototype.get=function(a){if(a=this.C(a)){if(a=a.data,!g.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};g.v(g.Td,Qd);g.Td.prototype.set=function(a,b,c){if(b=Sd(b)){if(c){if(c<(0,g.F)()){g.Td.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,g.F)()}g.Td.L.set.call(this,a,b)};
g.Td.prototype.C=function(a,b){var c=g.Td.L.C.call(this,a);if(c)if(!b&&g.Ud(c))g.Td.prototype.remove.call(this,a);else return c};g.v(g.Vd,g.Td);var ki,li;ki=new g.Nd;g.Xd=ki.isAvailable()?new g.Vd(ki):null;li=new Od;g.Wd=li.isAvailable()?new g.Vd(li):null;g.Uf=g.Za("Firefox");g.mi=g.pc()||g.Za("iPod");g.ni=g.Za("iPad");g.Dh=g.Za("Android")&&!(g.ab()||g.Za("Firefox")||g.Za("Opera")||g.Za("Silk"));g.Ch=g.ab();g.oi=g.Za("Safari")&&!(g.ab()||g.Za("Coast")||g.Za("Opera")||g.Za("Edge")||g.Za("Silk")||g.Za("Android"))&&!(g.pc()||g.Za("iPad")||g.Za("iPod"));g.Tba=g.ai||g.Dc&&!g.oi||g.Yh||"function"==typeof g.ea.btoa;g.Zd.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Zd.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Zd.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Eaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.$d=g.n("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.$d,void 0);var be=g.n("yt.events.counter_")||{count:0};g.m("yt.events.counter_",be,void 0);g.le=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;var xe={},Gaa=0;g.ye.prototype.Ob=function(){return{version:this.version,args:this.args}};
g.ze.prototype.toString=function(){return this.topic};var Uba=g.n("yt.pubsub2.instance_")||new g.rb;g.rb.prototype.subscribe=g.rb.prototype.subscribe;g.rb.prototype.unsubscribeByKey=g.rb.prototype.yd;g.rb.prototype.publish=g.rb.prototype.Ea;g.rb.prototype.clear=g.rb.prototype.clear;g.m("yt.pubsub2.instance_",Uba,void 0);g.pi=g.n("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.pi,void 0);g.qi=g.n("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.qi,void 0);g.ri=g.n("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.ri,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var mf=(0,g.F)().toString();var Me=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.v(Ce,g.ye);var Saa=new g.ze("timing-sent",Ce);g.f=g.De.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.De(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Ee(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.f=g.Fe.prototype;g.f.clone=function(){return new g.Fe(this.left,this.top,this.width,this.height)};
g.f.contains=function(a){return a instanceof g.nc?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.f.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};Ke.prototype.toString=function(){return this.region.toString()+": "+this.timing+" => "+this.url};
Le.prototype.toString=function(){return["progress",this.progress,"timing",this.timing,"area",this.yg].join(": ")};
Je.C=.1;Je.A=/url\(["']?(http[^'"\)]+)['"]?\)/i;Je.B="mark_iframe_loaded: ";Je.D=20;var Qaa={vc:!0},Jaa=/^mark_/i,df={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="player-plasma-phone/base"]':"mpppj",'script[name="player-plasma-tablet/base"]':"mpptj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},
Ye={ad_at:"adType",cpn:"clientPlaybackNonce",csn:"clientScreenNonce",yt_lt:"loadType",yt_ad:"isMonetized",yt_ad_pr:"prerollAllowed",yt_red:"isRedSubscriber",yt_vis:"isVisible"},Laa=["isMonetized","prerollAllowed","isRedSubscriber","isVisible"],Maa=(0,g.r)(Me.clearResourceTimings||Me.webkitClearResourceTimings||Me.mozClearResourceTimings||Me.msClearResourceTimings||Me.oClearResourceTimings||g.fa,Me);g.pf=/\s*;\s*/;g.f=g.of.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.pf),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.da(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Mb=g.ba(6);g.f.nb=g.ba(7);g.f.isEmpty=function(){return!this.A.cookie};
g.f.ob=g.ba(0);g.f.re=g.ba(8);g.f.clear=function(){for(var a=g.qf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.rf=new g.of("undefined"==typeof window.document?null:window.document);g.rf.C=3950;var Taa={enablejsapi:1},Uaa={},Vaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};xf.prototype.clone=function(){var a=new xf,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Va(c):a[b]=c}return a};g.zf=null;g.si=g.E?"focusin":"DOMFocusIn";g.ti=g.E?"focusout":"DOMFocusOut";g.ui=g.Dc?"webkitTransitionEnd":g.Yh?"otransitionend":"transitionend";g.vi=g.ai?"MozUserSelect":g.Dc||g.Zh?"WebkitUserSelect":null;g.ga(g.Kf);g.Kf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Waa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var cg;var wi=g.Ya,wi=wi.toLowerCase();if(g.za(wi,"android")){var xi=wi.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(xi)cg=Number(xi[1]);else{var yi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},zi=wi.match("("+g.Pa(yi).join("|")+")");cg=zi?yi[zi[0]]:0}}else cg=void 0;var Zaa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],$aa=['audio/mp4; codecs="mp4a.40.2"'];g.v(Qf,g.nb);Qf.prototype.Va=function(a){for(var b=0;b<this.A.length;b++)if(this.A[b]==a){this.A.splice(b,1);a.target.removeEventListener(a.name,a.Lb);break}};
Qf.prototype.U=function(){Sf(this);Qf.L.U.call(this)};var Xaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.v(Vf,g.nb);var Yaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=Vf.prototype;g.f.getId=function(){return this.ia};
g.f.Xo=function(a,b){this.gb()||(Xf(this,a),ag(this,b),this.H&&Yf(this))};
g.f.cA=function(){return this.jb};
g.f.cQ=function(){if(!this.aa){var a=dg(this);a&&"html5"==fg(this)?(this.G="html5",this.H||this.Xg()):(gg(this),this.G="html5",a&&this.M?(this.D.appendChild(this.M),this.Xg()):(this.A.loaded=!0,this.P=(0,g.r)(function(){var a=this.D,c=this.A.clone();g.n("yt.player.Application.create")(a,c);this.Xg()},this),this.aa=!0,a?this.P():(g.lc(this.A.assets.js,this.P),g.Pf(this.A.assets.css))))}};
g.f.bQ=function(){var a=this.A.clone();if(!this.F){var b=$f(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,Rf(this.ea,this.F,"focus",this.xu),this.R=window.document.createElement("span"),this.R.tabIndex=0,Rf(this.ea,this.R,"focus",this.xu),g.Ic(this.F,b),g.Jc(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==fg(this)?(this.G="flash",this.H||this.Xg()):(gg(this),this.G="flash",this.A.loaded=!0,b=g.Kf.getInstance(),b=g.Mf(b)||!g.Nf(b)?
a.url:a.urlV9As2,window!=window.top&&window.document.referrer&&(a.args.framer=window.document.referrer.substring(0,128)),g.Of(this.D,b,a),this.Xg())};
g.f.xu=function(){$f(this).focus()};
g.f.Xg=function(){if(!this.gb()){var a=$f(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))bg(this);else{Tf(this);this.H=!0;a=$f(this);a.addEventListener&&(this.T=eg(this,a,"addEventListener"));a.removeEventListener&&(this.la=eg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=eg(this,a,d))}for(var e in this.B)this.T(e,
this.B[e]);Yf(this);this.Ra&&this.Ra(this.api);this.X.Ea("onReady",this.api)}else this.xb=g.wb((0,g.r)(this.Xg,this),50)}};
g.f.qQ=function(){return this.H};
g.f.le=function(a,b){if(!this.gb()){var c=Wf(this,b);if(c){if(!g.Ja(this.Ib,a)&&!this.B[a]){var d=aba(this,a);this.T&&this.T(a,d)}this.X.subscribe(a,c);"onReady"==a&&this.H&&g.wb(g.t(c,this.api),0)}}};
g.f.iO=function(a,b){if(!this.gb()){var c=Wf(this,b);c&&this.X.unsubscribe(a,c)}};
g.f.ez=function(a){a=a?vaa:uaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.Hp=function(a){g.A("a11y-announce",a)};
g.f.SJ=function(a){bg(this,a)};
g.f.VJ=function(a){g.A("WATCH_LATER_VIDEO_ADDED",a)};
g.f.WJ=function(a){g.A("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.AJ=function(){this.bb||(g.Ch?(this.ab=g.Cc(window.document),Rf(this.Y,window,"scroll",this.pM),Rf(this.Y,this.D,"touchmove",this.PL)):(Rf(this.Y,this.D,"mousewheel",this.Mu),Rf(this.Y,this.D,"wheel",this.Mu)),this.bb=!0)};
g.f.BJ=function(){Sf(this.Y);this.bb=!1};
g.f.Mu=function(a){g.de(a)};
g.f.pM=function(){window.scrollTo(this.ab.x,this.ab.y)};
g.f.PL=function(a){a.preventDefault()};
g.f.VA=function(){return this.G||fg(this)};
g.f.FA=function(){return this.mb};
g.f.cancel=function(){if(this.P){var a=this.P,b=g.kc(this.A.assets.js);window.spf.script.ignore(b,a)}g.yb(this.xb);this.aa=!1};
g.f.U=function(){gg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Ab(b)}this.Wa=null;for(var a in this.B)g.ea[this.B[a]]=null;this.jb=this.A=this.api=null;delete this.D;delete this.K;Vf.L.U.call(this)};g.ig={};g.hg="player_uid_"+(1E9*Math.random()>>>0);var Vba=g.n("yt.abuse.botguardInitialized")||Af;g.m("yt.abuse.botguardInitialized",Vba,void 0);var Wba=g.n("yt.abuse.invokeBotguard")||g.Bf;g.m("yt.abuse.invokeBotguard",Wba,void 0);var Xba=g.n("yt.abuse.dclkstatus.checkDclkStatus")||Cf;g.m("yt.abuse.dclkstatus.checkDclkStatus",Xba,void 0);var Yba=g.n("yt.player.exports.navigate")||g.Ff;g.m("yt.player.exports.navigate",Yba,void 0);var Zba=g.n("yt.player.embed")||g.jg;g.m("yt.player.embed",Zba,void 0);var $ba=g.n("yt.player.getPlayerByElement")||g.kg;
g.m("yt.player.getPlayerByElement",$ba,void 0);var aca=g.n("yt.util.activity.init")||g.fe;g.m("yt.util.activity.init",aca,void 0);var bca=g.n("yt.util.activity.getTimeSinceActive")||g.ge;g.m("yt.util.activity.getTimeSinceActive",bca,void 0);var cca=g.n("yt.util.activity.setTimestamp")||ee;g.m("yt.util.activity.setTimestamp",cca,void 0);var ng,sg;g.rg=null;sg="";g.tg.prototype.stopPropagation=function(){this.hg=!0};
g.tg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Zv=!1};var Kg,eca;g.dca=!g.E||g.uc(9);Kg=!g.E||g.uc(9);eca=g.E&&!g.sc("9");!g.Dc||g.sc("528");g.ai&&g.sc("1.9b")||g.E&&g.sc("8")||g.Yh&&g.sc("9.5")||g.Dc&&g.sc("528");g.ai&&!g.sc("8")||g.E&&g.sc("9");g.v(g.ug,g.tg);
g.ug.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?g.ai&&(g.sa(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=g.Dc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Dc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Mn=g.bi?a.metaKey:a.ctrlKey;this.state=a.state;this.ub=a;a.defaultPrevented&&this.preventDefault()};
g.ug.prototype.stopPropagation=function(){g.ug.L.stopPropagation.call(this);this.ub.stopPropagation?this.ub.stopPropagation():this.ub.cancelBubble=!0};
g.ug.prototype.preventDefault=function(){g.ug.L.preventDefault.call(this);var a=this.ub;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,eca)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.ug.prototype.qr=g.ba(9);var vg="closure_listenable_"+(1E6*Math.random()|0),dba=0;yg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=zg(e,b,c,d);return-1<b?(xg(e[b]),g.Ka(e,b),0==e.length&&(delete this.A[a],this.C--),!0):!1};
yg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,xg(d[e]);delete this.A[c];this.C--}return b};var Hg="closure_lm_"+(1E6*Math.random()|0),Ng={},Jg=0,Qg="__closure_events_fn_"+(1E9*Math.random()>>>0);g.v(g.Rg,g.nb);g.Rg.prototype[vg]=!0;g.f=g.Rg.prototype;g.f.xj=function(){return this.Po};
g.f.Fi=g.ba(10);g.f.addEventListener=function(a,b,c,d){g.Dg(this,a,b,c,d)};
g.f.removeEventListener=function(a,b,c,d){g.Lg(this,a,b,c,d)};
g.f.dispatchEvent=function(a){var b,c=this.xj();if(c){b=[];for(var d=1;c;c=c.xj())b.push(c),++d}c=this.jy;d=a.type||a;if(g.ka(a))a=new g.tg(a,c);else if(a instanceof g.tg)a.target=a.target||c;else{var e=a;a=new g.tg(d,c);g.Xa(a,e)}var e=!0,h;if(b)for(var k=b.length-1;!a.hg&&0<=k;k--)h=a.currentTarget=b[k],e=Sg(h,d,!0,a)&&e;a.hg||(h=a.currentTarget=c,e=Sg(h,d,!0,a)&&e,a.hg||(e=Sg(h,d,!1,a)&&e));if(b)for(k=0;!a.hg&&k<b.length;k++)h=a.currentTarget=b[k],e=Sg(h,d,!1,a)&&e;return e};
g.f.U=function(){g.Rg.L.U.call(this);this.removeAllListeners();this.Po=null};
g.f.O=function(a,b,c,d){return g.Ag(this.Y,String(a),b,!1,c,d)};
g.f.Va=function(a,b,c,d){return this.Y.remove(String(a),b,c,d)};
g.f.removeAllListeners=function(a){return this.Y?this.Y.removeAll(a):0};g.v(g.Vg,g.nb);g.f=g.Vg.prototype;g.f.sb=0;g.f.U=function(){g.Vg.L.U.call(this);this.stop();delete this.A;delete this.C};
g.f.start=function(a){this.stop();this.sb=g.Tg(this.Lc,g.da(a)?a:this.B)};
g.f.stop=function(){this.isActive()&&g.Ug(this.sb);this.sb=0};
g.f.isActive=function(){return 0!=this.sb};
g.f.cm=function(){this.sb=0;this.A&&this.A.call(this.C)};var ah=[],bh=0,ch=0,Zg=[],Wg=0,$g={},Xg=new g.Vg(nba,1E3);var dh=null,gh=[];var kh,Bh,Ah,mh,lh,yba,rba,uba,sba,tba,wh;mh=0;lh=0;yba=["server_prefetched_vast","vmap"];rba=[900,60,"waiting"];uba=[500,99,"waiting"];sba=[300,60,"waiting"];tba=[400,99,"waiting"];wh=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.ub,void 0);g.m("yt.pushConfigArray",function(a,b){var c=g.x(a,void 0);c?c.push(b):g.ub(a,[b])},void 0);
g.m("yt.getConfig",g.x,void 0);g.m("yt.hasMsg",g.Cb,void 0);g.m("yt.pubsub.publish",g.A,void 0);g.m("yt.pubsub.subscribe",g.y,void 0);g.m("yt.setMsg",function(a){sb(g.Bb,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){sb(g.Bb,arguments)},void 0);
g.m("ytcsi.tick",g.Ue,void 0);g.v(Ih,g.Pb);
Ih.prototype.enable=function(){window.onload=pba;window.onunload=qba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",ih),window.addEventListener("spfhistory",jh),window.addEventListener("spfrequest",oh),window.addEventListener("spfpartprocess",sh),window.addEventListener("spfpartdone",th),window.addEventListener("spfprocess",uh),window.addEventListener("spfdone",xh),window.addEventListener("spferror",yh),window.addEventListener("spfreload",
zh),window.addEventListener("spfjsbeforeunload",Jh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",wba),this.subscribe("dispose",xba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Ih.prototype.init=function(){Ih.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.x("PAGEFRAME_JS")?(b=g.x("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.n("ytbin.www.pageframe.setup")()}):a&&(a=g.n("yt.www.masthead.loadSearchbox"))&&a();
var a=g.x("JS_COMMON_MODULE"),d=g.x("JS_PAGE_MODULES");d||(d=[a]);a=g.x("JS_DELAY_LOAD",0);0<a?(g.yb(this.B),this.B=g.wb(function(){b&&g.lc(b,c);window.spf.script.require(d)},a)):(b&&g.lc(b,c),window.spf.script.require(d));
cba();Paa();Kaa();kf(!0);g.Te(!1);g.x("SERVICE_WORKER_KILLSWITCH",void 0)||"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Qc("service_worker_enabled")?Cba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(Dba))};
Ih.prototype.dispose=function(){g.yb(this.B);var a=g.n("ytbin.www.pageframe.cancelSetup");a&&a();g.zb(ng);if(a=g.pg())a.removeEventListener("onReady",og),a.removeEventListener("onStateChange",og);kf(!1);Ih.L.dispose.call(this)};
Ih.prototype.disable=function(){Ih.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",ih),window.removeEventListener("spfhistory",jh),window.removeEventListener("spfrequest",oh),window.removeEventListener("spfpartprocess",sh),window.removeEventListener("spfpartdone",th),window.removeEventListener("spfprocess",uh),window.removeEventListener("spfdone",xh),window.removeEventListener("spferror",yh),window.removeEventListener("spfreload",zh),window.removeEventListener("spfjsbeforeunload",
Jh));window.onload=null;window.onunload=null;window.onerror=null};
g.Tb(new Ih);})(_yt_www);
